### ISSUE TITLE
pfscanV3 not working inside conodictor singularity container

### ISSUE THREAD

**Issue by jthiels** [koualab/conodictor#12]
pfscanV3 is giving 'index out of range' errors inside Singularity

When I ran 'singularity shell conodictor.sif pfscanV3 -h' on a compute node on the supercomputing cluster, I got an "Error setting affinity" error.  Note, pftools is 3.2.6 in the container.  According to this web page, the error can be fixed if pftools >=3.2.11: https://github.com/ebi-pf-team/interproscan/issues/231

**Expected behavior**
Help text output with pfscanV3 -h on a compute node

**Comment by Ebedthan** [comment]
Hi @jthiels ,
I'll take a look as soon as possible.
Thanks for reporting!

**Comment by jthiels** [comment]
Hi--what I've done to find a local solution is to build a Singularity container from the latest pftools Docker container and install hmmer and Python and then pip install conodictor.  This appears to work, except that I need to set CONODB when the container is initally built. In Docker, you can declare environment variables after the container is built; as a security measure in SIngularity, you have to do it in the build file for the variable to work

**Comment by Ebedthan** [comment]
Thanks @jthiels ,
I have updated the version in the Dockerfile.

**Comment by jthiels** [comment]
Thanks so much @Ebedthan!  Could you update it on dockerhub as well? It would be much appreciated!

**Comment by Ebedthan** [comment]
Done! @jthiels
